layout_spectrum: 0.2706767
color:
  saturation: 0.1004894
  brandStrength: 0.7421756
  lightness: 0.8088973
  rhythmicContrast: 0.8026316
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
typography_spectrum: 0.1522556
name: Justin Brochocki
